### ISSUE TITLE
플레이 페이지, 랭킹 페이지 라우팅

### ISSUE THREAD

**Issue by daehwan2** [code-etc/code-etc-worldcup-frontend#27]
라우팅을 어떤식으로 하는게 좋을까요?

/playWorldcup/gameid

/worldcup/rank/gameid

으로 하면 될까요?

**Comment by yunjin-kim** [comment]
월드컵 플레이
`worldcup/${gameid}`
월드컵 랭크
`worldcup/rank/${gameid}`

이렇게 하는 것은 어떨까요?
play 라는 단어는 붙이지 않아도 괜찮을 것 같아요
default가 게임을 플레이하는 것이니까요.

**Comment by daehwan2** [comment]
그렇게 적용해놓겠습니다
